# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.TextField(blank=True, db_index=True, null=True)),
                ('column_number', models.IntegerField(db_index=True, null=True)),
                ('is_binary_variable', models.BooleanField(default=False)),
                ('true_value', models.TextField(blank=True, db_index=True, null=True)),
                ('false_value', models.TextField(blank=True, db_index=True, null=True)),
                ('is_text_variable', models.BooleanField(default=False)),
                ('is_number_variable', models.BooleanField(default=False)),
                ('is_date_variable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('number', models.FloatField(null=True)),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Column')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_ID', models.TextField(blank=True, db_index=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('dataset_name', models.TextField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id_column', models.IntegerField(null=True)),
                ('date_column', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.TextField(blank=True, db_index=True, null=True)),
                ('row_number', models.IntegerField(db_index=True, null=True)),
                ('matches_filters', models.BooleanField(default=True)),
                ('matches_category', models.BooleanField(default=True)),
                ('matches_split', models.BooleanField(default=True)),
                ('matches_split_exclusions', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='RowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='coder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coder',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tag',
            field=models.ManyToManyField(to='coder_app.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='variable',
            field=models.ManyToManyField(to='coder_app.Variable'),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='freeform_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_freeform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_five',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_four',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_one',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_seven',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_six',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_three',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='multiple_choice_option_two',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variablelibrary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variablelibrary',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variablelibrary',
            name='variable',
            field=models.ManyToManyField(to='coder_app.Variable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contains_adverse_effects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rowstatus',
            name='coder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Coder'),
        ),
        migrations.AddField(
            model_name='data',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Dataset'),
        ),
        migrations.AddField(
            model_name='data',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Row'),
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Dataset'),
        ),
        migrations.AddField(
            model_name='project',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Dataset'),
        ),
        migrations.AlterIndexTogether(
            name='data',
            index_together=set([('dataset', 'row', 'column')]),
        ),
    ]
