# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='coder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Coder'),
        ),
        migrations.AddField(
            model_name='row',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='row',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
