# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0003_remove_data_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='curr_col_index',
            field=models.IntegerField(default=1),
        ),
    ]
