# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0003_rowmeta_row_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowmeta',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Project'),
        ),
    ]
