# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0005_auto_20171115_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contains_adverse_effects',
            new_name='contains_adverse_events',
        ),
    ]
