# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0007_data_coder'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='contains_adverse_events',
            field=models.BooleanField(default=False),
        ),
    ]
