# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0007_auto_20180103_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coder',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coder',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='coder',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='coder',
            name='username',
        ),
    ]
