# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0008_row_contains_adverse_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
