# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0008_auto_20180103_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
