# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0011_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_text_col_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='media_url_col_id',
            field=models.IntegerField(null=True),
        ),
    ]
