# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0011_auto_20171204_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
    ]
