# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0012_data_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='thing', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
