# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0012_auto_20180205_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
