# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0013_auto_20171206_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coder_app.Variable'),
        ),
    ]
