# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0015_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(to='coder_app.Project'),
        ),
    ]
